# Data Frame

So far we reviewed many types of object, from vector to list. In real world analysis, you'll need to work with square shaped data. For example, if you want to find best fit line, you must have pairs of x and y values. Something like you can represent in a table form.

Matrix was good starting point because it lets you use two dimensions. However, we had a issue with matrix that we can use only one type of data. As solution, we introduced a list that lets you mix different data types. But list is still not enough because we can't easily check if data across multiple components match in numbers to have clean number of (x, y) pairs. 

So what's the solution? Can we have two dimension data structure that allows us to store multiple data tye? That's where dataframe becomes useful. Dataframe, annotated as df, is a absolute highlight gem treasure in data analysis. It builds top of the list (so technically df is still a list) and adds solid 2D structure so that we can perform sophiscated calculations. 

## Factors and observation

Then, let's explore how R creates perfect (x,y) pairs for df. 
